# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d023be2d2366f9cad558423dbaeffe2b5cbda6c0d09dd101eda08e66b45f7479bcc4b69fe96c9aaf4bc4f0fd3f52ce3c620ad96d6acf970a5989fcc673b291d

test:
  secret_key_base: 2ec28d3bea1d674e248420fb0830092a6353daa0c3e3420ae7a019c0ea5376f7aa99629e2e74aebb094e836f6a1df1d16d5dfa7f63434118e9c0520c0bdb27f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
